#!/bin/sh
# SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
# SPDX-License-Identifier: LGPL-3.0-or-later

user_id=$(id -u) || exit 1

if /usr/bin/pgrep -u "$user_id" -x deepin-camera >/dev/null 2>&1; then
    exec /usr/bin/pkill -u "$user_id" -x deepin-camera
fi

exec /usr/bin/dde-am deepin-camera
